Project/connect alphavantage#load entity
kuber-dev/kuber pull request #57
Opened 2022-08-23 17:40 UTC by vbharadwaj09

Initial PR for basic load-entity implementation

2022-08-24 16:59 UTC, aloknigam247 commented
@vbharadwaj09  base branch should be project/connect-alphavantage and not main. but you won't be able to do it until you have a commit in your branch which differs the base branch. You can update base branch after creating a commit.

2022-08-29 05:13 UTC, aloknigam247 requested changes

2022-08-29 05:13 UTC, aloknigam247 commented on market/iexchange.py
> +    @classmethod
we can make it abstract forcing the derived exchange to implement it.

2022-08-29 05:13 UTC, aloknigam247 commented on market/iexchange.py
> +    def fetchEntity(cls, entity, timeline) -> dict:
`
```suggestion
    def fetchEntity(cls, entity: str, timeline: Timeline) -> Entity:
```
this method should return Entity object, otherwise Repository has to handle format of data per exchange. By putting this handling inside exchange, repository has abstract knowledge about the format of data coming from exchange.

2022-08-29 05:13 UTC, aloknigam247 commented on market/iexchange.py
> +            timeline: Timeline object. Has information from config.
`
```suggestion
            Timeline object, representing the timeline for which data has to be fetched
```

2022-08-29 05:13 UTC, aloknigam247 commented on market/iexchange.py
> +            Data in the form of json/dict. To decide...
```suggestion
            Entity object which has data for the timeline fetched
```

2022-08-29 05:13 UTC, aloknigam247 commented on market/market.py
> +        entity_list = []        # will be loaded from config.
we need to get list of entity from config

2022-08-29 05:13 UTC, aloknigam247 commented on market/market.py
> +        entity_data = self.repo.loadEntity(entity_list=entity_list, timeline=self.timeline)
loadEntity does not need to return data to market, though a return status in case of error could be usefull, but do we need return code or exception ?

2022-08-29 05:13 UTC, aloknigam247 commented on market/repository.py
> +            if entity not in self.entity_map.keys():
since its always loads first, we can abvoid this check

2022-08-29 05:13 UTC, aloknigam247 commented on market/repository.py
> +                self.entity_map[entity] = ent_data
should we use name as a key 🤔

2022-08-29 05:13 UTC, aloknigam247 commented on market/repository.py
> +
extra blank lines

2022-08-29 18:41 UTC, vbharadwaj09 commented on market/market.py
> +        entity_data = self.repo.loadEntity(entity_list=entity_list, timeline=self.timeline)
I think returning False, with a descriptive log from fetchEntity should be sufficient..

2022-08-29 18:44 UTC, vbharadwaj09 commented on market/repository.py
> +                self.entity_map[entity] = ent_data
That seems to be a valid approach.
entity name comes from config as a string, and we can use the same throughout the framework
If any module requests data we can easily return the entity object from the repo.

2022-08-29 18:55 UTC, vbharadwaj09 commented on market/market.py
> +        entity_list = []        # will be loaded from config.
Need to finalize the configuration file...
How to store entities?? They can be dependent on market/exchanges.
Are we supposed to validate that as well??

2022-09-01 15:33 UTC, aloknigam247 approved these changes

2022-09-01 15:34 UTC, merged